### ISSUE TITLE
LG 2-7 Dependencies vs. Coupling

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/curriculum-foundation#301] opened 2022-10-30 11:20 UTC
I propose to change the line 
     "understand how dependencies increase coupling" 
to 
     "understand that coupling is the degree of interdependency between building blocks"
and move this so that it is the first (instead of the second) building block.

Aren't "dependencies" and "coupling" synonyms? Can you have a coupling without a dependency? Are there other things besides dependencies that increase coupling?

According to Wikipedia (I know, not the best source, just an example):

Coupling is:
- 
the degree of interdependence between software modules;
- a measure of how closely connected two routines or modules are;
- the strength of the relationships between modules

**Comment by alxlo** [comment] 2022-11-09 19:39
Dependency is a know concept to our participants, they know it from a programmers perspective. But they think mostly about usage, call, etc. When we talk about coupling we introduce (from their perspective) a more general concept of dependencies. 

So from an educator's point of view it is useful to keep both terms, start out with dependencies, talk about coupling and then come full circle to explain that when components are coupled, there are, well, dependencies that should show up on your radar.

The problem is that we 
* have to live with an only party consistent terminology, that we cannot simply reduce to *the* most appropriate term
* we don't deal with coupling in a very scientific and correct manner (we don't have to and we can't in the time that we have)

**Comment by ulibecker** [comment] 2022-11-09 21:10
I agree with @alxlo

**Comment by gernotstarke** [comment] 2022-11-10 06:46
I agree with @alxlo too, therefore I propose to close the issue and keep LG 2-7 (nearly) as-is.

Therefore, I close this.

**Closed by gernotstarke** 2022-11-10 06:46 UTC
Labels: wontfix, learning content, V2023

**Comment by gernotstarke** [comment] 2022-11-14 13:30
that's an overly theoretical definition. Several kinds of coupling cannot be measured, therefore coupling in general cannot be a "degree". But I'm nitpicking ...

**Comment by rhoadesre** [comment] 2022-11-14 14:05
> that's an overly theoretical definition. Several kinds of coupling cannot be measured, therefore coupling in general cannot be a "degree". But I'm nitpicking ...

I'm fine with "Coupling refers to the interdependence between software building blocks"
